
### Get All Comments
GET http://localhost:3000/api/v1/comment

### Create Comment
POST http://localhost:3000/api/v1/comment
Content-Type: application/json

{
   "userId": "clke101t50000rcvk6be0pqf2",
   "body": "Hey it's good!!!",
   "productId": "clke2t14x000crc8bqt15scna"
}

